src/webui/service/device/forms.py
# Copyright 2021-2023 H2020 TeraFlow (https://www.teraflow-h2020.eu/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# external imports
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length, NumberRange, Regexp, ValidationError

from webui.utils.form_validators import key_value_validator
from webui.proto.context_pb2 import (DeviceDriverEnum, DeviceOperationalStatusEnum)

class AddDeviceForm(FlaskForm):
    device_id = StringField('ID', 
                           validators=[DataRequired(), Length(min=5)])
    device_type = StringField('Type', 
                           validators=[DataRequired(), Length(min=5)])
    device_config = TextAreaField('Configurations', validators=[key_value_validator()])
    operational_status = SelectField('Operational Status',
                        #    choices=[(-1, 'Select...'), (0, 'Undefined'), (1, 'Disabled'), (2, 'Enabled')],
                           coerce=int,
                           validators=[NumberRange(min=0)])
    device_drivers = TextAreaField('Drivers', validators=[DataRequired(), Regexp(r'^\d+(,\d+)*$')])
    submit = SubmitField('Add')

    def validate_operational_status(form, field):
        if field.data not in DeviceOperationalStatusEnum.DESCRIPTOR.values_by_number:
            raise ValidationError('The operational status value selected is incorrect!')
    
    def validate_device_drivers(form, field):
        if ',' not in field.data:
            data = str(field.data) + ','
        else:
            data = field.data
        for value in data.split(','):
            value = value.strip()
            if len(value) == 0:
                continue
            try:
                value_int = int(value)
            except:
                raise ValidationError(f'The value "{value}" is not a valid driver identified.')
            if value_int not in DeviceDriverEnum.DESCRIPTOR.values_by_number:
                values = ', '.join([str(x) for x in DeviceDriverEnum.DESCRIPTOR.values_by_number])
                raise ValidationError(f'The device driver {value_int} is not correct. Allowed values are: {values}.')

src/webui/service/device/__init__.py
# Copyright 2021-2023 H2020 TeraFlow (https://www.teraflow-h2020.eu/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

src/webui/service/device/routes.py
# Copyright 2021-2023 H2020 TeraFlow (https://www.teraflow-h2020.eu/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from flask import render_template, Blueprint, flash, session, redirect
from device.client.DeviceClient import DeviceClient
from context.client.ContextClient import ContextClient
from webui.Config import (CONTEXT_SERVICE_ADDRESS, CONTEXT_SERVICE_PORT,
                DEVICE_SERVICE_ADDRESS, DEVICE_SERVICE_PORT)
from webui.proto.context_pb2 import (ContextId, DeviceList, DeviceId,
    Device, DeviceDriverEnum, DeviceOperationalStatusEnum,
    ConfigActionEnum, ConfigRule, TopologyIdList, TopologyList)
from webui.service.device.forms import AddDeviceForm

device = Blueprint('device', __name__, url_prefix='/device')
context_client: ContextClient = ContextClient(CONTEXT_SERVICE_ADDRESS, CONTEXT_SERVICE_PORT)
device_client: DeviceClient = DeviceClient(DEVICE_SERVICE_ADDRESS, DEVICE_SERVICE_PORT)

@device.get('/')
def home():
    request: ContextId = ContextId()
    request.context_uuid.uuid = session.get('context_uuid', '-')
    context_client.connect()
    response: DeviceList = context_client.ListDevices(request)
    context_client.close()
    return render_template('device/home.html', devices=response.devices,
                                               dde=DeviceDriverEnum,
                                               dose=DeviceOperationalStatusEnum)

@device.route('add', methods=['GET', 'POST'])
def add():
    form = AddDeviceForm()

    request: ContextId = ContextId()
    request.context_uuid.uuid = session.get('context_uuid', '-')
    context_client.connect()
    response: TopologyIdList = context_client.ListTopologyIds(request)
    context_client.close()

    # listing enum values
    form.operational_status.choices = [(-1, 'Select...')]
    for key, value in DeviceOperationalStatusEnum.DESCRIPTOR.values_by_name.items():
        form.operational_status.choices.append((DeviceOperationalStatusEnum.Value(key), key.replace('DEVICEOPERATIONALSTATUS_', '')))
    
    # device driver ids
    device_driver_ids = []
    for key in DeviceDriverEnum.DESCRIPTOR.values_by_name:
        device_driver_ids.append(f"{DeviceDriverEnum.Value(key)}={key.replace('DEVICEDRIVER_', '')}")
    device_driver_ids = ', '.join(device_driver_ids)

    if form.validate_on_submit():
        device: Device = Device()
        device.device_id.device_uuid.uuid = form.device_id.data
        device.device_type = form.device_type.data
        if '\n' not in form.device_config.data:
            data = form.device_config.data.strip() + '\n'
        else:
            data = form.device_config.data.strip()
        
        for config in data.split('\n'):
            if len(config.strip()) > 0:
                parts = config.strip().split('=')
                config_rule: ConfigRule = ConfigRule()
                config_rule.action = ConfigActionEnum.CONFIGACTION_SET
                config_rule.resource_key = parts[0].strip()
                config_rule.resource_value = parts[1].strip()
                device.device_config.config_rules.append(config_rule)

        device.device_operational_status = form.operational_status.data

        if ',' not in form.device_drivers.data:
            data = form.device_drivers.data.strip() + ','
        else:
            data = form.device_drivers.data.strip()
        
        for driver in data.split(','):
            driver = driver.strip()
            if len(driver) == 0:
                continue
            device.device_drivers.append(int(driver))
        try:
            device_client.connect()
            response: DeviceId = device_client.AddDevice(device)
            device_client.close()

            flash(f'New device was created with ID "{response.device_uuid.uuid}".', 'success')
            return redirect('/device/')
        except Exception as e:
            flash(f'Problem adding the device. {e.details()}', 'danger')
        
    return render_template('device/add.html', form=form,
                    submit_text='Add New Device',
                    device_driver_ids=device_driver_ids)

@device.route('detail/<device_uuid>', methods=['GET', 'POST'])
def detail(device_uuid: str):
    request: DeviceId = DeviceId()
    request.device_uuid.uuid = device_uuid
    context_client.connect()
    response: Device = context_client.GetDevice(request)
    context_client.close()
    return render_template('device/detail.html', device=response)

@device.get('<device_uuid>/delete')
def delete(device_uuid):
    try:

        # first, check if device exists!
        # request: DeviceId = DeviceId()
        # request.device_uuid.uuid = device_uuid
        # response: Device = client.GetDevice(request)
        # TODO: finalize implementation

        request: DeviceId = DeviceId()
        request.device_uuid.uuid = device_uuid
        device_client.connect()
        response = device_client.DeleteDevice(request)

        device_client.close()

        flash('Device deleted successfully!', 'success')
    except Exception as e:
        flash(f'Problem deleting the device. {e.details()}', 'danger')

    return redirect('/device/')

src/webui/service/templates/device/add.html
<!--
 Copyright 2021-2023 H2020 TeraFlow (https://www.teraflow-h2020.eu/)

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

{% extends 'base.html' %}

{% block content %}
    <h1>Add New Device</h1>

    <form id="add_device" method="POST">
        {{ form.hidden_tag() }}
        <fieldset>
            <div class="row mb-3">
                {{ form.device_id.label(class="col-sm-2 col-form-label") }}
                <div class="col-sm-10">
                  {% if form.device_id.errors %}
                        {{ form.device_id(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.device_id.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.device_id(class="form-control") }}
                    {% endif %}
                </div>
            </div>
            <div class="row mb-3">
                {{ form.device_type.label(class="col-sm-2 col-form-label") }}
                <div class="col-sm-10">
                  {% if form.device_type.errors %}
                        {{ form.device_type(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.device_type.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.device_type(class="form-control") }}
                    {% endif %}
                </div>
            </div>
            <div class="row mb-3">
                {{ form.operational_status.label(class="col-sm-2 col-form-label") }}
                <div class="col-sm-10">
                  {% if form.operational_status.errors %}
                        {{ form.operational_status(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.operational_status.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.operational_status(class="form-control") }}
                    {% endif %}
                </div>
            </div>
            <div class="row mb-3">
                {{ form.device_config.label(class="col-sm-2 col-form-label") }}
                <div class="col-sm-10">
                  {% if form.device_config.errors %}
                        {{ form.device_config(class="form-control is-invalid", rows=5) }}
                        <div class="invalid-feedback">
                            {% for error in form.device_config.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.device_config(class="form-control", rows=5) }}
                    {% endif %}
                </div>
                <div id="device_config_help" class="form-text">The device configurations should follow a <i>key=value</i> format, one configuration per line.</div>
            </div>
            <div class="row mb-3">
                {{ form.device_drivers.label(class="col-sm-2 col-form-label") }}
                <div class="col-sm-10">
                  {% if form.device_drivers.errors %}
                        {{ form.device_drivers(class="form-control is-invalid", rows=5) }}
                        <div class="invalid-feedback">
                            {% for error in form.device_drivers.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.device_drivers(class="form-control", rows=5) }}
                    {% endif %}
                </div>
                <div id="device_drivers_help" class="form-text">
                    List the device drivers by their numerical ID, separated by commas, without spaces between them. Numerical IDs: {{ device_driver_ids }}.
                </div>
            </div>
            <div class="row mb-3">
                <button type="submit" class="btn btn-primary">{{ submit_text }}</button>
            </div>
        </fieldset>
    </form>
{% endblock %}

src/webui/service/templates/device/detail.html
<!--
 Copyright 2021-2023 H2020 TeraFlow (https://www.teraflow-h2020.eu/)

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

{% extends 'base.html' %}

{% block content %}
    <h1>Device {{ device.device_id.device_uuid.uuid }}</h1>

    <div class="row mb-3">
        <div class="col-sm-3">
            <button type="button" class="btn btn-success" onclick="window.location.href = '/device/'"><i class="bi bi-box-arrow-in-left"></i>Back to device list</button>
        </div>
        <div class="col-sm-3">
            <a id="update" class="btn btn-secondary" href="#"><i class="bi bi-pencil-square"></i>Update</a>
        </div>
        <div class="col-sm-3">
            <!-- <button type="button" class="btn btn-danger"><i class="bi bi-x-square"></i>Delete device</button> -->
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">
                <i class="bi bi-x-square"></i>Delete device
              </button>
        </div>
    </div>

    <div class="row mb-3">
        <b>UUID:</b>
        <div class="col-sm-10">
            {{ device.device_id.device_uuid.uuid }}
        </div>
    </div>
    <div class="row mb-3">
        <b>Type:</b>
        <div class="col-sm-10">
            {{ device.device_type }}
        </div>
    </div>
    <div class="row mb-3">
        <b>Configurations:</b>
        <div class="col-sm-10">
            <ul>
            {% for config in device.device_config.config_rules %}
                <li>{{ config.resource_key }}: {{ config.resource_value }}</li>
            {% endfor %}
            </ul>
        </div>
    </div>
    <div class="row mb-3">
        <b>Endpoints:</b>
        <div class="col-sm-10">
            <ul>
            {% for endpoint in device.device_endpoints %}
                <li>{{ endpoint.endpoint_id.endpoint_uuid.uuid }}: {{ endpoint.endpoint_type }}</li>
            {% endfor %}
            </ul>
        </div>
    </div>

    <!-- Modal -->
<div class="modal fade" id="deleteModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Delete device?</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Are you sure you want to delete the device "{{ device.device_id.device_uuid.uuid }}"?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
          <a type="button" class="btn btn-danger" href="{{ url_for('device.delete', device_uuid=device.device_id.device_uuid.uuid) }}"><i class="bi bi-exclamation-diamond"></i>Yes</a>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

src/webui/service/templates/device/home.html
<!--
 Copyright 2021-2023 H2020 TeraFlow (https://www.teraflow-h2020.eu/)

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

{% extends 'base.html' %}

{% block content %}
    <h1>Devices</h1>

    <div class="row">
        <div class="col">
            <a href="{{ url_for('device.add') }}" class="btn btn-primary" style="margin-bottom: 10px;">
                <i class="bi bi-plus"></i>
                Add New Device
            </a>
        </div>
        <div class="col">
            {{ devices | length }} devices found in context <i>{{ session['context_uuid'] }}</i>
        </div>
        <!-- <div class="col">
            <form>
                <div class="input-group">
                    <input type="text" aria-label="Search" placeholder="Search..." class="form-control"/>
                    <button type="submit" class="btn btn-primary">Search</button>
                  </div>
            </form>
        </div> -->
    </div>

    <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Type</th>
            <th scope="col">Endpoints</th>
            <th scope="col">Drivers</th>
            <th scope="col">Status</th>
            <th scope="col">Configuration</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
            {% if devices %}
                {% for device in devices %}
                <tr>
                    <td>
                        <!-- <a href="{{ url_for('device.detail', device_uuid=device.device_id.device_uuid.uuid) }}"> -->
                            {{ device.device_id.device_uuid.uuid }}
                        <!-- </a> -->
                    </td>
                    <td>
                        {{ device.device_type }}
                    </td>
                    <td>
                        <ul>
                            {% for end_point in device.device_endpoints %}
                            <li>{{ end_point.endpoint_id.endpoint_uuid.uuid }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>
                        <ul>
                            {% for driver in device.device_drivers %}
                            <li>{{ dde.Name(driver).replace('DEVICEDRIVER_', '') }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>{{ dose.Name(device.device_operational_status).replace('DEVICEOPERATIONALSTATUS_', '') }}</td>
                    <td>
                        <ul>
                            {% for config in device.device_config.config_rules %}
                            <li>
                                Key: {{ config.resource_key }}<br/>
                                Value: {{ config.resource_value }}
                            </li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>
                        <a href="{{ url_for('device.detail', device_uuid=device.device_id.device_uuid.uuid) }}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                                <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
                                <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
                            </svg>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="7">No devices found</td>
                </tr>
            {% endif %}
        </tbody>
    </table>

{% endblock %}